# Generated by Django 6.0.7 on 2026-08-06 21:29

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_site'),
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('contact_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='nom du contact')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='adresse e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='téléphone')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='adresse')),
                ('tax_number', models.CharField(blank=True, max_length=30, null=True, verbose_name="numéro d'identification fiscale")),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='customer_name_unique_ci')],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='référence')),
                ('customer_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='client')),
                ('customer_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='adresse')),
                ('customer_tax_number', models.CharField(blank=True, max_length=30, null=True, verbose_name="numéro d'identification fiscale")),
                ('status', models.CharField(choices=[('COMPLETED', 'Finalisée'), ('CANCELLED', 'Annulée')], default='COMPLETED', max_length=16, verbose_name='statut')),
                ('subtotal', models.PositiveIntegerField(default=0, verbose_name='sous-total')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='remise')),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='taux de remise')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='total')),
                ('vat_total', models.PositiveIntegerField(default=0, verbose_name='TVA')),
                ('note', models.CharField(blank=True, max_length=300, null=True, verbose_name='note')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='annulée le')),
                ('cancel_reason', models.CharField(blank=True, max_length=300, null=True, verbose_name="motif d'annulation")),
                ('user_name', models.CharField(max_length=150, verbose_name='auteur')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.customer', verbose_name='client')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='accounts.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vente',
                'verbose_name_plural': 'ventes',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(verbose_name='montant')),
                ('method', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile money'), ('BANK_TRANSFER', 'Virement bancaire'), ('CARD', 'Carte'), ('OTHER', 'Autre')], max_length=20, verbose_name='moyen')),
                ('paid_at', models.DateTimeField(verbose_name='payé le')),
                ('reference', models.CharField(blank=True, max_length=40, null=True, verbose_name='référence')),
                ('note', models.CharField(blank=True, max_length=300, null=True, verbose_name='note')),
                ('user_name', models.CharField(max_length=150, verbose_name='auteur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.sale', verbose_name='vente')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['paid_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article_name', models.CharField(max_length=120, verbose_name='article')),
                ('article_sku', models.CharField(max_length=32, verbose_name='référence')),
                ('unit', models.CharField(choices=[('PIECE', 'Pièce'), ('KG', 'Kilogramme'), ('LITRE', 'Litre'), ('PAQUET', 'Paquet'), ('CARTON', 'Carton')], max_length=8, verbose_name='unité')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantité')),
                ('unit_price', models.PositiveIntegerField(verbose_name='prix unitaire')),
                ('unit_cost', models.PositiveIntegerField(verbose_name='coût unitaire')),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='taux de TVA')),
                ('line_total', models.PositiveIntegerField(verbose_name='total ligne')),
                ('discount_share', models.PositiveIntegerField(default=0, verbose_name='part de remise')),
                ('vat_amount', models.PositiveIntegerField(default=0, verbose_name='TVA')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='catalogue.article')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale', verbose_name='vente')),
            ],
            options={
                'verbose_name': 'ligne de vente',
                'verbose_name_plural': 'lignes de vente',
            },
        ),
    ]
