# Generated by Django 6.0.7 on 2026-08-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='identifiant client'),
        ),
    ]
