# Generated by Django 6.0.7 on 2026-08-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_client_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='client_uuid',
        ),
    ]
