# Generated by Django 6.0.7 on 2026-10-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_sale_client_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleline',
            name='unit',
            field=models.CharField(choices=[('PIECE', 'Pièce'), ('KG', 'Kilogramme'), ('METRE', 'Mètre'), ('LITRE', 'Litre'), ('PAQUET', 'Paquet'), ('CARTON', 'Carton')], max_length=8, verbose_name='unité'),
        ),
    ]
