# Generated by Django 6.0.7 on 2026-08-03 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('address', models.TextField(verbose_name='adresse')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='adresse e-mail')),
                ('tax_number', models.CharField(blank=True, max_length=100, null=True, verbose_name="numéro d'identification fiscale")),
                ('invoice_footer', models.TextField(blank=True, null=True, verbose_name='pied de facture')),
                ('is_default', models.BooleanField(default=True, verbose_name='établissement par défaut')),
            ],
            options={
                'verbose_name': 'établissement',
                'verbose_name_plural': 'établissements',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_site')],
            },
        ),
    ]
