# Generated by Django 6.0.7 on 2026-08-13 21:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('install_id', models.UUIDField(unique=True, verbose_name="identifiant d'installation")),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='code')),
                ('label', models.CharField(max_length=60, verbose_name='libellé')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='vu pour la dernière fois')),
            ],
            options={
                'verbose_name': 'appareil',
                'verbose_name_plural': 'appareils',
                'ordering': ['code'],
            },
        ),
    ]
