# Generated by Django 6.0.7 on 2026-08-06 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_site'),
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie'), ('ADJUSTMENT', 'Ajustement')], max_length=16, verbose_name='type')),
                ('reason', models.CharField(choices=[('PURCHASE', 'Achat fournisseur'), ('SALE', 'Vente'), ('RETURN', 'Retour'), ('DAMAGE', 'Casse'), ('LOSS', 'Perte'), ('COUNT_CORRECTION', "Correction d'inventaire"), ('OTHER', 'Autre')], max_length=20, verbose_name='motif')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantité')),
                ('quantity_before', models.PositiveIntegerField(verbose_name='quantité avant')),
                ('quantity_after', models.PositiveIntegerField(verbose_name='quantité après')),
                ('unit_cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='coût unitaire')),
                ('reference', models.CharField(blank=True, max_length=40, null=True, verbose_name='référence')),
                ('note', models.CharField(blank=True, max_length=300, null=True, verbose_name='note')),
                ('user_name', models.CharField(max_length=150, verbose_name='auteur')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalogue.article')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='accounts.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mouvement de stock',
                'verbose_name_plural': 'mouvements de stock',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantité')),
                ('reorder_threshold', models.PositiveIntegerField(default=0, verbose_name='seuil de réapprovisionnement')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='catalogue.article', verbose_name='article')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='accounts.site')),
            ],
            options={
                'verbose_name': 'niveau de stock',
                'verbose_name_plural': 'niveaux de stock',
                'constraints': [models.UniqueConstraint(fields=('article', 'site'), name='one_stock_level_per_article_and_site')],
            },
        ),
    ]
