# Generated by Django 6.0.7 on 2026-08-06 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_site'),
        ('catalogue', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='référence')),
                ('user_reference', models.CharField(blank=True, max_length=40, null=True, verbose_name='référence du document')),
                ('type', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie'), ('ADJUSTMENT', 'Ajustement')], max_length=16, verbose_name='type')),
                ('reason', models.CharField(choices=[('PURCHASE', 'Achat fournisseur'), ('SALE', 'Vente'), ('RETURN', 'Retour'), ('DAMAGE', 'Casse'), ('LOSS', 'Perte'), ('COUNT_CORRECTION', "Correction d'inventaire"), ('OTHER', 'Autre')], max_length=20, verbose_name='motif')),
                ('supplier_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='fournisseur')),
                ('note', models.CharField(blank=True, max_length=300, null=True, verbose_name='note')),
                ('line_count', models.PositiveIntegerField(default=0, verbose_name='nombre de lignes')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='quantité totale')),
                ('user_name', models.CharField(max_length=150, verbose_name='auteur')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.site')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='catalogue.supplier', verbose_name='fournisseur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transaction de stock',
                'verbose_name_plural': 'transactions de stock',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='stock.stocktransaction', verbose_name='transaction'),
        ),
    ]
