# Generated by Django 6.0.7 on 2026-08-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockmovement_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklevel',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantité'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity_after',
            field=models.IntegerField(verbose_name='quantité après'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity_before',
            field=models.IntegerField(verbose_name='quantité avant'),
        ),
    ]
