# Generated by Django 6.0.7 on 2026-08-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stocklevel_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='identifiant client'),
        ),
    ]
