# Generated by Django 6.0.7 on 2026-08-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=8)),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'séquence de document',
                'verbose_name_plural': 'séquences de document',
                'constraints': [models.UniqueConstraint(fields=('prefix', 'year'), name='one_sequence_per_prefix_and_year')],
            },
        ),
    ]
