# Generated by Django 6.0.7 on 2026-08-06 12:16

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, verbose_name='nom')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='category_name_unique_ci')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('contact_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='nom du contact')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='adresse e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='téléphone')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='adresse')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'fournisseur',
                'verbose_name_plural': 'fournisseurs',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='supplier_name_unique_ci')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=32, verbose_name='référence')),
                ('barcode', models.CharField(blank=True, max_length=13, null=True, verbose_name='code-barres')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('unit', models.CharField(choices=[('PIECE', 'Pièce'), ('KG', 'Kilogramme'), ('LITRE', 'Litre'), ('PAQUET', 'Paquet'), ('CARTON', 'Carton')], default='PIECE', max_length=8, verbose_name='unité')),
                ('purchase_price', models.PositiveIntegerField(default=0, verbose_name="prix d'achat")),
                ('sale_price', models.PositiveIntegerField(default=0, verbose_name='prix de vente')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='taux de TVA')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='catalogue.category', verbose_name='catégorie')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='catalogue.supplier', verbose_name='fournisseur')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('sku'), name='article_sku_unique_ci'), models.UniqueConstraint(models.F('barcode'), condition=models.Q(('barcode__isnull', False)), name='article_barcode_unique')],
            },
        ),
    ]
