# Generated by Django 6.0.7 on 2026-08-08 14:53

from django.db import migrations, models

from apps.catalogue.name_sort import rebuild_name_sort


def backfill(apps, schema_editor):
    """Populate `name_sort` for rows that predate the column.

    This imports application code, which is normally worth avoiding because the
    import is pinned to today's behaviour. It is the right trade here: if
    `collation_key` ever changes, existing values are stale and a *new*
    backfill migration is required regardless — editing this historical one
    would not help.
    """
    rebuild_name_sort(
        apps.get_model("catalogue", "Category"),
        apps.get_model("catalogue", "Supplier"),
        apps.get_model("catalogue", "Article"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['name_sort'], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name_sort'], 'verbose_name': 'catégorie', 'verbose_name_plural': 'catégories'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name_sort'], 'verbose_name': 'fournisseur', 'verbose_name_plural': 'fournisseurs'},
        ),
        migrations.AddField(
            model_name='article',
            name='name_sort',
            field=models.CharField(db_index=True, default='', editable=False, max_length=240),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sort',
            field=models.CharField(db_index=True, default='', editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='supplier',
            name='name_sort',
            field=models.CharField(db_index=True, default='', editable=False, max_length=160),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
