# Generated by Django 6.0.7 on 2026-10-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_seed_article_sku_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='unit',
            field=models.CharField(choices=[('PIECE', 'Pièce'), ('KG', 'Kilogramme'), ('METRE', 'Mètre'), ('LITRE', 'Litre'), ('PAQUET', 'Paquet'), ('CARTON', 'Carton')], default='PIECE', max_length=8, verbose_name='unité'),
        ),
    ]
