# Generated by Django 6.0.7 on 2026-08-08 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('RENT', 'Loyer'), ('SALARY', 'Salaires'), ('UTILITIES', 'Eau et électricité'), ('TRANSPORT', 'Transport'), ('SUPPLIES', 'Fournitures'), ('TAX', 'Taxes et impôts'), ('OTHER', 'Autre')], max_length=16, verbose_name='catégorie')),
                ('label', models.CharField(max_length=120, verbose_name='libellé')),
                ('amount', models.PositiveIntegerField(verbose_name='montant')),
                ('method', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile money'), ('BANK_TRANSFER', 'Virement bancaire'), ('CARD', 'Carte'), ('OTHER', 'Autre')], max_length=20, verbose_name='moyen')),
                ('spent_at', models.DateTimeField(verbose_name='dépensé le')),
                ('reference', models.CharField(blank=True, max_length=40, null=True, verbose_name='référence')),
                ('note', models.CharField(blank=True, max_length=500, null=True, verbose_name='note')),
                ('user_name', models.CharField(max_length=150, verbose_name='auteur')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounts.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'charge',
                'verbose_name_plural': 'charges',
                'ordering': ['-spent_at', '-id'],
            },
        ),
    ]
